### ISSUE TITLE
Twio errors while ignoring phenomizer and boqa

### ISSUE THREAD

**Issue by la60312** [PEDIA-Charite/PEDIA-workflow#66]
There two bugs in ignoring phenomizer.
1. If I delete phenomizer block in config.ini
```
Traceback (most recent call last):
  File "./preprocess.py", line 383, in <module>
    main()
  File "./preprocess.py", line 340, in main
    config_data = config.PEDIAConfig(args)
  File "/home/la60312/pedia3/PEDIA-workflow/lib/model/config.py", line 47, in __init__
    PHENOMIZER_INST.configure(**self.phenomizer_options)
  File "/home/la60312/pedia3/PEDIA-workflow/lib/model/config.py", line 76, in phenomizer_options
    "url": self["phenomizer"]["url"],
  File "/home/la60312/miniconda3/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'phenomizer'
```
2. if we run the following command without phenomizer
./preprocess.py -s process/aws_dir/cases/73413.json -o output
You will find lots of NaN. Could you replace them with 0?
```
            "gestalt_score": NaN,
            "feature_score": NaN,
            "combined_score": NaN,
            "pheno_score": 0.0,
            "boqa_score": 0.0,
```

**Comment by la60312** [comment]
Do you have time to check this? Face2Gene is waiting. If you don't have time, I will do it.

**Comment by la60312** [comment]
ade0b9f1d8ccd803f0bbb13bcf54441bcb45bd07
